apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scratch-pvc
  namespace: scratch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 142.5Gi
  volumeName: scratch-pv
  storageClassName: ""  # Must match the PV
