apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prometheus-secret-bundle
  namespace: monitoring
spec:
  provider: oci
  parameters:
    authType: instance
    vaultId: ${VAULT_ID}

    secrets: |
      - name: "grafana-login-user"
        fileName: "grafana-login-user"
      - name: "grafana-login-password"
        fileName: "grafana-login-password"

  secretObjects:
    - secretName: prometheus-secret
      type: Opaque
      data:
        - objectName: "grafana-login-user"
          key: GF_USER
        - objectName: "grafana-login-password"
          key: GF_PASSWORD
