apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlflow-secret-bundle
  namespace: mlflow
spec:
  provider: oci
  parameters:
    authType: instance
    vaultId: ${VAULT_ID}

    secrets: |
      - name: "mlflow-db-uri"
        fileName: "mlflow-db-uri"

  secretObjects:
    - secretName: mlflow-secret
      type: Opaque
      data:
        - objectName: mlflow-db-uri
          key: MLFLOW_DB_URI
