apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlflow-secret-bundle
  namespace: mlflow
spec:
  provider: oci
  parameters:
    authType: instance
    vaultId: ocid1.vault.oc1.eu-frankfurt-1.enukrh6baabfg.abtheljstyfpr62x56uvsbvxol7wemw7b2qrt5jmj727thp4wiumcvit536a

    secrets: |
      - name: "oci-access-key"
        fileName: "oci-access-key"
      - name: "oci-secret-key"
        fileName: "oci-secret-key"
      - name: "oci-namespace"
        fileName: "oci-namespace"
      - name: "oci-s3-endpoint"
        fileName: "oci-s3-endpoint"
      - name: "mlflow-db-uri"
        fileName: "mlflow-db-uri"

  secretObjects:
    - secretName: mlflow-secret
      type: Opaque
      data:
        - objectName: oci-access-key
          key: OCI_ACCESS_KEY
        - objectName: oci-secret-key
          key: OCI_SECRET_KEY
        - objectName: oci-namespace
          key: OCI_NAMESPACE
        - objectName: oci-s3-endpoint
          key: OCI_S3_ENDPOINT
        - objectName: mlflow-db-uri
          key: MLFLOW_DB_URI
