apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oci-secrets-store-csi-driver-provider-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
