apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oci-secrets-store-csi-driver-provider
  namespace: kube-system
  labels:
    app.kubernetes.io/name: oci-secrets-store-csi-driver-provider
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: oci-secrets-store-csi-driver-provider
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oci-secrets-store-csi-driver-provider
    spec:
      serviceAccountName: oci-secrets-store-csi-driver-provider-sa
      containers:
        - name: oci-secrets-store-csi-driver-provider
          image: ghcr.io/trading-engineering/oci-secrets-store-csi-driver-provider:latest
          imagePullPolicy: Always
          args:
            - --endpoint=unix:///opt/provider/sockets/oci.sock
            - --endpoint-permissions=0755
            - --healthz-port=8098
            - --metrics-port=8198
          env:
            - name: OCI_RESOURCE_PRINCIPAL_VERSION
              value: "2.2"
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 0
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: "/opt/provider/sockets"
              name: socket-volume
      volumes:
        - name: socket-volume
          hostPath:
            path: /var/run/secrets-store-csi-providers
