apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: default
spec:
  project: default

  source:
    repoURL: https://github.com/trading-engineering/trading-infrastructure
    targetRevision: fix/configmap
    path: apps/argo/overlays/runtime

  destination:
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
