apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scratch-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/trading-engineering/trading-infrastructure
    targetRevision: main
    path: apps/scratch/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
