apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secret-bundle
  namespace: postgres
spec:
  provider: oci
  parameters:
    authType: instance
    vaultId: ocid1.vault.oc1.eu-frankfurt-1.enukrh6baabfg.abtheljstyfpr62x56uvsbvxol7wemw7b2qrt5jmj727thp4wiumcvit536a

    secrets: |
      - name: "postgresdb-naming"
        fileName: "postgresdb-naming"
      - name: "postgres-user"
        fileName: "postgres-user"
      - name: "postgres-password"
        fileName: "postgres-password"
      - name: "mlflowdb-naming"
        fileName: "mlflowdb-naming"
      - name: "mlflow-user"
        fileName: "mlflow-user"
      - name: "mlflow-password"
        fileName: "mlflow-password"

  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: postgresdb-naming
          key: POSTGRES_DB
        - objectName: postgres-user
          key: POSTGRES_USER
        - objectName: postgres-password
          key: POSTGRES_PASSWORD
        - objectName: "mlflowdb-naming"
          key: MLFLOW_DB
        - objectName: mlflow-user
          key: MLFLOW_USER
        - objectName: mlflow-password
          key: MLFLOW_PASSWORD
